[tool.ruff]
target-version = "py310"
line-length = 100
fix = true
select = ["E", "F", "I", "UP", "C90", "B"]
exclude = ["venv", "__pycache__", "migrations", "data", "notebooks"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"
indent-style = "space"
line-ending = "auto"
